Repository devjeans-si-d/Si-D-server, pull requests merged in 2024-08, with the labels that each got.

#24 Feat/IS-28 메인페이지 프로젝트, 완성프로젝트, 회원리스트 조회 api
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/SaveLaunchedProjectRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/TempReqeust.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProject.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectRepository.java
  src/main/java/org/devjeans/sid/domain/mainPage/controller/MainPageController.java
  src/main/java/org/devjeans/sid/domain/mainPage/dto/TopListLaunchedProjectResponse.java
  src/main/java/org/devjeans/sid/domain/mainPage/dto/TopListMemberResponse.java
  src/main/java/org/devjeans/sid/domain/mainPage/dto/TopListProjectResponse.java
  src/main/java/org/devjeans/sid/domain/mainPage/service/MainPageService.java
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/entity/Member.java
  src/main/java/org/devjeans/sid/domain/member/repository/MemberRepository.java
  src/main/java/org/devjeans/sid/domain/project/entity/JobField.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
  src/main/java/org/devjeans/sid/domain/project/entity/ProjectMember.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectRepository.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/SiderCard.java
  src/main/java/org/devjeans/sid/domain/siderCard/repository/SiderCardRepository.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/SiderCardExceptionType.java
  src/main/resources/.DS_Store
Labels: ✨ feature

#27 feat/ IS-31: 사이더카드 목록,상세조회 구현
  src/main/java/org/devjeans/sid/domain/siderCard/controller/SiderCardController.java
  src/main/java/org/devjeans/sid/domain/siderCard/dto/SiDCardListDto.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/SiderCard.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/TechStack.java
  src/main/java/org/devjeans/sid/domain/siderCard/service/SiderCardService.java
Labels: ✨ feature

#29 feat/IS-25 조회수 생성/조회 및 스크랩 생성/삭제/조회(프로젝트 상세, 전체조회 포함) 구현
  src/main/java/org/devjeans/sid/config/RedisConfig.java
  src/main/java/org/devjeans/sid/domain/project/controller/ProjectController.java
  src/main/java/org/devjeans/sid/domain/project/dto/create/createListRequest/CreateProjectMemberRequest.java
  src/main/java/org/devjeans/sid/domain/project/dto/create/createListRequest/CreateRecruitInfoRequest.java
  src/main/java/org/devjeans/sid/domain/project/dto/read/DetailProjectResponse.java
  src/main/java/org/devjeans/sid/domain/project/dto/read/ListProjectResponse.java
  src/main/java/org/devjeans/sid/domain/project/dto/scrap/ScrapResponse.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
  src/main/java/org/devjeans/sid/domain/project/entity/ProjectScrap.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectRepository.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectScrapRepository.java
  src/main/java/org/devjeans/sid/domain/project/service/ProjectScheduler.java
  src/main/java/org/devjeans/sid/domain/project/service/ProjectService.java
  src/main/java/org/devjeans/sid/domain/project/service/ScrapService.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/ScrapProjectException.java
Labels: ✨ feature

#30 feat/IS-29: 프로젝트 지원하기, 자신의 지원 목록 조회, 자신이 참여한 프로젝트 목록 조회 API
  src/main/java/org/devjeans/sid/domain/launchedProject/controller/LaunchedProjectController.java
  src/main/java/org/devjeans/sid/domain/project/ProjectAcceptController.java
  src/main/java/org/devjeans/sid/domain/project/controller/ProjectAcceptController.java
  src/main/java/org/devjeans/sid/domain/project/dto/ApplicantResponse.java
  src/main/java/org/devjeans/sid/domain/project/dto/ApplicationResponse.java
  src/main/java/org/devjeans/sid/domain/project/dto/ApplyProjectRequest.java
  src/main/java/org/devjeans/sid/domain/project/dto/ApplyProjectResponse.java
  src/main/java/org/devjeans/sid/domain/project/dto/MyProjectResponse.java
  src/main/java/org/devjeans/sid/domain/project/entity/ProjectApplication.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectApplicationRepository.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectMemberRepository.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectRepository.java
  src/main/java/org/devjeans/sid/domain/project/service/ProjectAcceptService.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/ProjectAcceptException.java
Labels: ✨ feature

#31 Feat/IS-30 : Redis 이용 스크랩 추가/삭제/조회 api, 조회수 조회, 스케쥴러로 RDB에 업데이트
  src/main/java/org/.DS_Store
  src/main/java/org/devjeans/.DS_Store
  src/main/java/org/devjeans/sid/.DS_Store
  src/main/java/org/devjeans/sid/config/RedisConfig.java
  src/main/java/org/devjeans/sid/domain/.DS_Store
  src/main/java/org/devjeans/sid/domain/launchedProject/controller/LaunchedProjectController.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/BasicInfoLaunchedProjectResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchedProjectScrapDTO/LaunchedProjectScrapRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchedProjectScrapDTO/LaunchedProjectScrapResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProject.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProjectScrap.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/ToggleStatus.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectScrapRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/service/LaunchedProjectScheduler.java
  src/main/java/org/devjeans/sid/domain/launchedProject/service/LaunchedProjectScrapService.java
  src/main/java/org/devjeans/sid/domain/launchedProject/service/LaunchedProjectService.java
  src/main/java/org/devjeans/sid/domain/launchedProject/service/LaunchedProjectViewService.java
  src/main/java/org/devjeans/sid/domain/member/.DS_Store
  src/main/java/org/devjeans/sid/global/exception/exceptionType/LaunchedProjectScrapExceptionType.java
Labels: ✨ feature

#34 fix/IS-48: 멤버 정보 조회, 수정 API 변경
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/service/MemberService.java
  src/main/java/org/devjeans/sid/global/external/mail/service/EmailService.java
Labels: 🚧 fix

#35 fix/IS-49: 프로젝트 엔티티에 imageUrl 추가, MyProjectResponse 응답값 수정
  src/main/java/org/devjeans/sid/domain/project/dto/MyProjectResponse.java
  src/main/java/org/devjeans/sid/domain/project/entity/JobField.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
Labels: 🚧 fix

#36 fix/IS-50: ApplicationResponse 응답 값 수정
  src/main/java/org/devjeans/sid/domain/project/dto/ApplicationResponse.java
Labels: 🚧 fix

#38 fix/IS-52: 웹 소켓 채팅 관련 코드 수정
  src/main/java/org/devjeans/sid/config/SecurityConfigs.java
  src/main/java/org/devjeans/sid/domain/auth/JwtTokenProvider.java
  src/main/java/org/devjeans/sid/domain/chatRoom/component/ConnectedMap.java
  src/main/java/org/devjeans/sid/domain/chatRoom/component/StompHandler.java
  src/main/java/org/devjeans/sid/domain/chatRoom/controller/ChatController.java
  src/main/java/org/devjeans/sid/domain/chatRoom/controller/WebSocketController.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/ChatMessageRequest.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatMessageRepository.java
  src/main/java/org/devjeans/sid/domain/chatRoom/service/ChatService.java
  src/main/java/org/devjeans/sid/domain/chatRoom/service/WebSocketService.java
  src/main/resources/static/chat.html
  src/main/resources/static/chatfront/chat1.html
Labels: 🚧 fix

#39 feat: 이메일 변경 코드 수정
  src/main/resources/templates/emailVerification.html
Labels: 🚧 fix

#40 chore: 인증 메일 링크 변경
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/service/MemberService.java
  src/main/resources/docker-compose/docker-compose-local.yml
  src/main/resources/templates/emailVerification.html
Labels: 🚧 fix

#43 chore:완성된 프로젝트 imageUrl string으로 수정 및 스크랩 서비스 삭제 기능 수정
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/BasicInfoLaunchedProjectResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/ListLaunchedProjectResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/SaveLaunchedProjectRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProject.java
  src/main/java/org/devjeans/sid/domain/project/service/ScrapService.java
Labels: 🚧 fix

#44 fix: 내 프로젝트 목록 페이지네이션으로 변경
  src/main/java/org/devjeans/sid/domain/project/controller/ProjectAcceptController.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectMemberRepository.java
  src/main/java/org/devjeans/sid/domain/project/service/ProjectAcceptService.java
  src/main/resources/docker-compose/docker-compose-local.yml
Labels: 🚧 fix

#46 feat/IS-65 fix : 메인페이지 TopMemberList api 수정
  src/main/java/org/devjeans/sid/domain/mainPage/dto/TopListMemberResponse.java
  src/main/java/org/devjeans/sid/domain/mainPage/service/MainPageService.java
  src/main/java/org/devjeans/sid/domain/member/entity/Member.java
Labels: 🚧 fix

#83 Enhance/IS-138: 채팅에 펍섭 추가
  src/main/java/org/devjeans/sid/SiDApplication.java
  src/main/java/org/devjeans/sid/domain/chatRoom/controller/RedisSubscriber.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/ChatRoomMessageResponse.java
  src/main/resources/application.yml
Labels: 🍀 enhancement
