Repository devjeans-si-d/Si-D-server, pull requests merged in 2024-07, with the labels that each got.

#3 Feat/IS-1: 엔티티 작업
  build.gradle
  src/main/java/org/devjeans/sid/domain/career/entity/Career.java
  src/main/java/org/devjeans/sid/domain/career/entity/EmployedYn.java
  src/main/java/org/devjeans/sid/domain/chatMessage/entity/ChatMessage.java
  src/main/java/org/devjeans/sid/domain/chatParticipant/entity/ChatParticipant.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatRoom.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProject.java
  src/main/java/org/devjeans/sid/domain/launchedProjectMember/entity/LaunchedProjectMember.java
  src/main/java/org/devjeans/sid/domain/launchedProjectScrap/entity/LaunchedProjectScrap.java
  src/main/java/org/devjeans/sid/domain/launchedProjectTechStack/entity/LaunchedProjectTechStack.java
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/entity/Member.java
  src/main/java/org/devjeans/sid/domain/member/entity/SocialType.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
  src/main/java/org/devjeans/sid/domain/projectMember/entity/ProjectMember.java
  src/main/java/org/devjeans/sid/domain/projectScrap/entity/ProjectScrap.java
  src/main/java/org/devjeans/sid/domain/recruitInfo/entity/RecruitInfo.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/SiderCard.java
  src/main/java/org/devjeans/sid/domain/siderCardTechStack/entity/SiderCardTechStack.java
  src/main/java/org/devjeans/sid/domain/socialInfo/entity/Platform.java
  src/main/java/org/devjeans/sid/domain/socialInfo/entity/SocialInfo.java
  src/main/java/org/devjeans/sid/domain/techStack/entity/JobField.java
  src/main/java/org/devjeans/sid/domain/techStack/entity/TechStack.java
  src/main/resources/application.yml
Labels: ✨ feature

#2 Feat/IS-2: 에러 응답 관련 작업
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/global/exception/BaseException.java
  src/main/java/org/devjeans/sid/global/exception/ErrorResponse.java
  src/main/java/org/devjeans/sid/global/exception/GlobalExceptionHandler.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/ExceptionType.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/MemberExceptionType.java
Labels: ✨ feature

#5 feat/IS-5: 엔티티 리팩토링 & repository 생성
  src/main/java/org/devjeans/sid/domain/career/repository/CareerRepository.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatMessage.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatParticipant.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatMessageRepository.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatParticipantRepository.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatRoomRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProjectMember.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProjectScrap.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProjectTechStack.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectMemberRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectScrapRepository.java
  src/main/java/org/devjeans/sid/domain/member/repository/MemberRepository.java
  src/main/java/org/devjeans/sid/domain/project/entity/ProjectMember.java
  src/main/java/org/devjeans/sid/domain/project/entity/ProjectScrap.java
  src/main/java/org/devjeans/sid/domain/project/entity/RecruitInfo.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectMemberRepository.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectRepository.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectScrapRepository.java
  src/main/java/org/devjeans/sid/domain/project/repository/RecruitInfoRepository.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/JobField.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/Platform.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/SiderCardTechStack.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/SocialInfo.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/TechStack.java
  src/main/java/org/devjeans/sid/domain/siderCard/repository/SiderCardRepository.java
  src/main/java/org/devjeans/sid/domain/siderCard/repository/SiderCardTechStackRepository.java
  src/main/java/org/devjeans/sid/domain/siderCard/repository/SocialInfoRepository.java
  src/main/java/org/devjeans/sid/domain/siderCard/repository/TechStackRepository.java
Labels: 🧹refactor

#6 feat/IS-9: 멤버 정보 조회, 멤버 정보 수정 API 구현
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/dto/MemberInfoResponse.java
  src/main/java/org/devjeans/sid/domain/member/dto/UpdateMemberRequest.java
  src/main/java/org/devjeans/sid/domain/member/dto/UpdateMemberResponse.java
  src/main/java/org/devjeans/sid/domain/member/entity/Member.java
  src/main/java/org/devjeans/sid/domain/member/repository/MemberRepository.java
  src/main/java/org/devjeans/sid/domain/member/service/MemberService.java
  src/main/java/org/devjeans/sid/global/exception/GlobalExceptionHandler.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/MemberExceptionType.java
Labels: ✨ feature

#7 feat/IS-10: 채팅방 목록 조회 & 채팅 내용 조회 API 작성
  src/main/java/org/devjeans/sid/domain/chatRoom/chatService/ChatService.java
  src/main/java/org/devjeans/sid/domain/chatRoom/controller/ChatController.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/ChatRoomListResponse.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/ChatRoomMessageResponse.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/ChatRoomSimpleResponse.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatMessage.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatParticipant.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatRoom.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatMessageRepository.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatParticipantRepository.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatRoomRepository.java
  src/main/java/org/devjeans/sid/domain/common/BaseEntity.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/ChatExceptionType.java
Labels: ✨ feature

#9 feat/IS-12: 회원등록 api 구현, RegisterMemberRequest dto 추가
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/dto/RegisterMemberRequest.java
  src/main/java/org/devjeans/sid/domain/member/entity/Member.java
  src/main/java/org/devjeans/sid/domain/member/service/MemberService.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/SiderCard.java
Labels: ✨ feature

#10 feat/IS-11: 채팅방 생성, 입장, 채팅 보내기 기능 구현
  .gitignore
  build.gradle
  src/main/java/org/devjeans/sid/config/WebConfig.java
  src/main/java/org/devjeans/sid/config/WebSocketConfig.java
  src/main/java/org/devjeans/sid/domain/chatRoom/component/ConnectedMap.java
  src/main/java/org/devjeans/sid/domain/chatRoom/component/StompHandler.java
  src/main/java/org/devjeans/sid/domain/chatRoom/component/WebSocketEventListener.java
  src/main/java/org/devjeans/sid/domain/chatRoom/controller/ChatController.java
  src/main/java/org/devjeans/sid/domain/chatRoom/controller/ChatRoomValue.java
  src/main/java/org/devjeans/sid/domain/chatRoom/controller/WebSocketController.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/ChatMessageRequest.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/ChatRoomSimpleResponse.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/CreateChatRoomRequest.java
  src/main/java/org/devjeans/sid/domain/chatRoom/dto/CreateChatRoomResponse.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatMessage.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatParticipant.java
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatRoom.java
  src/main/java/org/devjeans/sid/domain/chatRoom/repository/ChatRoomRepository.java
  src/main/java/org/devjeans/sid/domain/chatRoom/service/ChatService.java
  src/main/java/org/devjeans/sid/domain/chatRoom/service/SseService.java
  src/main/java/org/devjeans/sid/domain/chatRoom/service/WebSocketService.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectRepository.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/ChatExceptionType.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/ProjectExceptionType.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/SseExceptionType.java
Labels: ✨ feature

#11 Fix/IS-14: 회원 정보 업데이터 API 수정
  src/main/java/org/devjeans/sid/domain/chatRoom/entity/ChatMessage.java
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/service/MemberService.java
Labels: 🚧 fix

#12 Feat/is 7 LaunchedProject Create(완성된프로젝트 글 등록)api
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/org/devjeans/sid/domain/launchedProject/controller/LaunchedProjectController.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/BasicInfoLaunchedProjectResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/ListLaunchedProjectResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/SaveLaunchedProjectRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/UpdateLaunchedProjectRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchedProjectMemberDTO/LaunchedProjectMemberRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchedProjectMemberDTO/LaunchedProjectMemberResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchedProjectScrapDTO/LaunchedProjectScrapRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchedProjectScrapDTO/LaunchedProjectScrapResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchedProjectTechStackDTO/LaunchedProjectTechStackResponse.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/TempReqeust.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProject.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProjectMember.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProjectScrap.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProjectTechStack.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectMemberRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectScrapRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/service/LaunchedProjectService.java
  src/main/java/org/devjeans/sid/domain/member/entity/Member.java
  src/main/java/org/devjeans/sid/domain/member/repository/MemberRepository.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
  src/main/java/org/devjeans/sid/domain/project/entity/ProjectMember.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectRepository.java
  src/main/java/org/devjeans/sid/domain/siderCard/entity/TechStack.java
  src/main/java/org/devjeans/sid/domain/siderCard/repository/TechStackRepository.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/LaunchedProjectExceptionType.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/TechStackExceptionType.java
  src/main/resources/application.yml
Labels: ✨ feature

#16 feat/IS-16: memberId를 가져오는 SecurityUtil 생성
  build.gradle
  src/main/java/org/devjeans/sid/domain/auth/JwtAuthfilter.java
  src/main/java/org/devjeans/sid/domain/chatRoom/service/ChatService.java
  src/main/java/org/devjeans/sid/domain/member/entity/Role.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/AuthException.java
  src/main/java/org/devjeans/sid/global/util/SecurityUtil.java
Labels: ✨ feature

#17 feat/IS-15: 수신 이메일 인증 메일 보내기 & 이메일 변경 API 작성
  .gitignore
  build.gradle
  src/main/java/org/devjeans/sid/config/MailConfig.java
  src/main/java/org/devjeans/sid/config/RedisConfig.java
  src/main/java/org/devjeans/sid/domain/auth/service/AuthService.java
  src/main/java/org/devjeans/sid/domain/member/controller/MemberController.java
  src/main/java/org/devjeans/sid/domain/member/dto/MemberIdEmailCode.java
  src/main/java/org/devjeans/sid/domain/member/dto/UpdateEmailRequest.java
  src/main/java/org/devjeans/sid/domain/member/dto/UpdateEmailResponse.java
  src/main/java/org/devjeans/sid/domain/member/entity/Member.java
  src/main/java/org/devjeans/sid/domain/member/service/MemberService.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/MemberExceptionType.java
  src/main/java/org/devjeans/sid/global/external/mail/service/EmailService.java
  src/main/resources/application.yml
  src/main/resources/static/chatfront/chat1.html
  src/main/resources/templates/emailVerification.html
Labels: ✨ feature

#19 Enhance/IS-18: 웹 소켓 채팅 시 jwt 토큰 검증 로직 추가
  build.gradle
  src/main/java/org/devjeans/sid/config/SecurityConfigs.java
  src/main/java/org/devjeans/sid/domain/auth/JwtTokenProvider.java
  src/main/java/org/devjeans/sid/domain/auth/controller/AuthController.java
  src/main/java/org/devjeans/sid/domain/chatRoom/component/ConnectedMap.java
  src/main/java/org/devjeans/sid/domain/chatRoom/component/StompHandler.java
  src/main/resources/static/chat.html
Labels: 🍀 enhancement, 🚧 fix

#22 feat/IS-22: 자신의 프로젝트에 지원한 멤버 조회, 승인
  src/main/java/org/devjeans/sid/domain/auth/controller/AuthController.java
  src/main/java/org/devjeans/sid/domain/project/ProjectAcceptController.java
  src/main/java/org/devjeans/sid/domain/project/dto/AcceptApplicantRequest.java
  src/main/java/org/devjeans/sid/domain/project/dto/ApplicantResponse.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
  src/main/java/org/devjeans/sid/domain/project/entity/ProjectApplication.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectApplicationRepository.java
  src/main/java/org/devjeans/sid/domain/project/repository/ProjectMemberRepository.java
  src/main/java/org/devjeans/sid/domain/project/service/ProjectAcceptService.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/ProjectAcceptException.java
  src/main/java/org/devjeans/sid/global/external/mail/service/EmailService.java
  src/main/resources/templates/acceptNotification.html
Labels: ✨ feature

#23 fix/IS-27: 런칭된 프로젝트 글 등록 / 업데이트 로직 수정 & S3 presigned url 방식 업로드 구현
  .DS_Store
  build.gradle
  src/main/java/org/devjeans/sid/config/S3Config.java
  src/main/java/org/devjeans/sid/domain/launchedProject/controller/LaunchedProjectController.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/SaveLaunchedProjectRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/dto/LaunchProjectDTO/UpdateLaunchedProjectRequest.java
  src/main/java/org/devjeans/sid/domain/launchedProject/entity/LaunchedProject.java
  src/main/java/org/devjeans/sid/domain/launchedProject/repository/LaunchedProjectRepository.java
  src/main/java/org/devjeans/sid/domain/launchedProject/service/LaunchedProjectService.java
  src/main/java/org/devjeans/sid/domain/project/entity/Project.java
  src/main/java/org/devjeans/sid/global/exception/exceptionType/LaunchedProjectExceptionType.java
  src/main/java/org/devjeans/sid/global/external/imageUpload/controller/ImageUploadController.java
  src/main/java/org/devjeans/sid/global/external/imageUpload/dto/PresignedRequest.java
  src/main/java/org/devjeans/sid/global/external/imageUpload/service/FileService.java
Labels: ✨ feature, 🚧 fix
